# Generated by Django 5.0 on 2023-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20231221_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebig',
            name='title_en',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='coursebig',
            name='title_uz',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='courselittle1',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='courselittle1',
            name='title_uz',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='courselittle2',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courselittle2',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courselittle2',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='courselittle2',
            name='title_uz',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
