# Generated by Django 3.2.10 on 2023-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('authuser', '0002_auto_20231220_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.CourseBig'),
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
